USE [master]
GO
/****** Object:  Database [TPFINAL-BIBLIOTECA]    Script Date: 11/24/2024 3:55:46 PM ******/
CREATE DATABASE [TPFINAL-BIBLIOTECA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TPFINAL-BIBLIOTECA', FILENAME = N'C:\SQL Express\MSSQL16.SQLEXPRESS\MSSQL\DATA\TPFINAL-BIBLIOTECA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TPFINAL-BIBLIOTECA_log', FILENAME = N'C:\SQL Express\MSSQL16.SQLEXPRESS\MSSQL\DATA\TPFINAL-BIBLIOTECA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TPFINAL-BIBLIOTECA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ARITHABORT OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET  ENABLE_BROKER 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET  MULTI_USER 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET QUERY_STORE = ON
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TPFINAL-BIBLIOTECA]
GO
/****** Object:  Table [dbo].[ALUMNOS]    Script Date: 11/24/2024 3:55:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ALUMNOS](
	[DNI_ALUMNO] [int] NOT NULL,
	[NOMBRE_COMPLETO] [nvarchar](255) NOT NULL,
	[DIRECCION] [nvarchar](255) NULL,
	[TELEFONO] [nvarchar](50) NULL,
	[EMAIL] [nvarchar](100) NULL,
	[FECHA_REGISTRO] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[DNI_ALUMNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LIBROS]    Script Date: 11/24/2024 3:55:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LIBROS](
	[ID_LIBRO] [int] IDENTITY(1,1) NOT NULL,
	[TITULO] [nvarchar](255) NOT NULL,
	[AUTOR] [nvarchar](255) NOT NULL,
	[GENERO] [nvarchar](100) NULL,
	[CANTIDAD_DISPONIBLE] [int] NOT NULL,
 CONSTRAINT [PK__LIBROS__93FF0A0626EE1F0F] PRIMARY KEY CLUSTERED 
(
	[ID_LIBRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRESTAMOS]    Script Date: 11/24/2024 3:55:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRESTAMOS](
	[ID_PRESTAMO] [int] IDENTITY(1,1) NOT NULL,
	[ID_LIBRO] [int] NOT NULL,
	[DNI_ALUMNO] [int] NOT NULL,
	[FECHA_PRESTAMO] [date] NOT NULL,
	[FECHA_DEVOLUCION] [date] NULL,
 CONSTRAINT [PK__PRESTAMO__3D5A1E6C7DAE31EA] PRIMARY KEY CLUSTERED 
(
	[ID_PRESTAMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[ALUMNOS] ([DNI_ALUMNO], [NOMBRE_COMPLETO], [DIRECCION], [TELEFONO], [EMAIL], [FECHA_REGISTRO]) VALUES (12345678, N'Carlos Pérez', N'Av. Libertador 1234, Buenos Aires', N'1123456789', N'carlos.perez@email.com', CAST(N'2024-11-01' AS Date))
GO
INSERT [dbo].[ALUMNOS] ([DNI_ALUMNO], [NOMBRE_COMPLETO], [DIRECCION], [TELEFONO], [EMAIL], [FECHA_REGISTRO]) VALUES (23456789, N'Laura Gómez', N'Calle Ficticia 567, Córdoba', N'1167894560', N'laura.gomez@email.com', CAST(N'2024-11-02' AS Date))
GO
INSERT [dbo].[ALUMNOS] ([DNI_ALUMNO], [NOMBRE_COMPLETO], [DIRECCION], [TELEFONO], [EMAIL], [FECHA_REGISTRO]) VALUES (34567890, N'Martín Rodríguez', N'Ruta Nacional 45, Rosario', N'1134567890', N'martin.rodriguez@email.com', CAST(N'2024-11-03' AS Date))
GO
INSERT [dbo].[ALUMNOS] ([DNI_ALUMNO], [NOMBRE_COMPLETO], [DIRECCION], [TELEFONO], [EMAIL], [FECHA_REGISTRO]) VALUES (45678901, N'Ana López', N'Calle Real 987, Mendoza', N'1145678901', N'ana.lopez@email.com', CAST(N'2024-11-04' AS Date))
GO
INSERT [dbo].[ALUMNOS] ([DNI_ALUMNO], [NOMBRE_COMPLETO], [DIRECCION], [TELEFONO], [EMAIL], [FECHA_REGISTRO]) VALUES (56789012, N'Pedro Fernández', N'Av. 9 de Julio 234, Tucumán', N'1198765432', N'pedro.fernandez@email.com', CAST(N'2024-11-05' AS Date))
GO
SET IDENTITY_INSERT [dbo].[LIBROS] ON 
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (1, N'Introducción a la programación en C#', N'John Doe', N'Programación', 5)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (2, N'Fundamentos de bases de datos', N'Jane Smith', N'Base de datos', 3)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (3, N'Algoritmos y estructuras de datos', N'Mark Johnson', N'Programación', 7)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (4, N'Redes de computadoras', N'Paul Brown', N'Redes', 4)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (5, N'Sistemas operativos modernos', N'Linda White', N'Sistemas', 6)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (6, N'Arquitectura de computadoras', N'Robert Green', N'Hardware', 8)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (7, N'Cálculo y álgebra lineal', N'Emily Taylor', N'Matemáticas', 2)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (8, N'Fundamentos de inteligencia artificial', N'Michael Lee', N'Inteligencia Artificial', 4)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (9, N'Desarrollo de aplicaciones móviles', N'David Harris', N'Programación', 6)
GO
INSERT [dbo].[LIBROS] ([ID_LIBRO], [TITULO], [AUTOR], [GENERO], [CANTIDAD_DISPONIBLE]) VALUES (10, N'Seguridad informática', N'Susan Clark', N'Seguridad', 5)
GO
SET IDENTITY_INSERT [dbo].[LIBROS] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__ALUMNOS__161CF7249EADA072]    Script Date: 11/24/2024 3:55:46 PM ******/
ALTER TABLE [dbo].[ALUMNOS] ADD UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRESTAMOS]  WITH CHECK ADD  CONSTRAINT [FK_AlumnoID] FOREIGN KEY([DNI_ALUMNO])
REFERENCES [dbo].[ALUMNOS] ([DNI_ALUMNO])
GO
ALTER TABLE [dbo].[PRESTAMOS] CHECK CONSTRAINT [FK_AlumnoID]
GO
ALTER TABLE [dbo].[PRESTAMOS]  WITH CHECK ADD  CONSTRAINT [FK_LibroID] FOREIGN KEY([ID_LIBRO])
REFERENCES [dbo].[LIBROS] ([ID_LIBRO])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRESTAMOS] CHECK CONSTRAINT [FK_LibroID]
GO
USE [master]
GO
ALTER DATABASE [TPFINAL-BIBLIOTECA] SET  READ_WRITE 
GO
